# ======================================================
# The Correct render.yaml for a Django Application
# ======================================================

# 1. Define the Database first, under its own top-level key
databases:
  - name: my-accounting-db
    plan: free
    databaseName: myaccountingdb # The actual name for the database
    user: myuser         # The user for the database

# 2. Define the Web Service second, under its own top-level key
services:
  - type: web
    name: my-accounting-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project_core.wsgi:application"
    healthCheckPath: /api/login/
    envVars:
      - key: DATABASE_URL
        fromDatabase: # <-- This key correctly links to the database block above
          name: my-accounting-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
