services:
  # The Database Service
  - type: psql # <-- FIX: The type was "postgres", it should be "psql"
    name: my-accounting-db
    plan: free
    postgresmajorVersion: "14"

  # The Web Service (Our Django App)
  - type: web
    name: my-accounting-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project_core.wsgi:application"
    healthCheckPath: /api/login/
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql # <-- This should also be updated to match
          name: my-accounting-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
